### ISSUE TITLE
Compile for gpu use failed at GPU Objectives

### ISSUE THREAD

**Issue by hsukiang** [voutcn/megahit#138]
Hello there,

I m trying to compile megahit for GPU usage. However it failed at this stage. I am using POWER8 server and CUDA 8.0 on Ubuntu16.04.
Am I missing a library and NVCC could not locate? 
 
~/project/megahit# make use_gpu=1
"/usr/local/cuda-8.0/bin/nvcc"  -arch=sm_35 lv2_gpu_functions.cu -Xptxas -v -Xcudafe -# -cuda --ptxas-options=-v -Xptxas -abi=no -mpowerpc64 -I"/usr/local/cuda-8.0/bin/../include" -I.  -O3 -DTUNE_ARCH=350 -DTUNE_SIZE=4 -o .lv2_gpu_functions_4B_sm350_nvvm_8.0_abi_ppc64.cpp 
nvcc fatal   : 'powerpc64': expected a number
Makefile:253: recipe for target '.lv2_gpu_functions_4B_sm350_nvvm_8.0_abi_ppc64.cpp' failed
make: *** [.lv2_gpu_functions_4B_sm350_nvvm_8.0_abi_ppc64.cpp] Error 1

Thank you!

Best regards,
James

**Comment by aquaskyline** [comment]
Hi James, could you please use the CPU version? The CPU version using 8 cores is in fact faster than the CPU version.

**Comment by hsukiang** [comment]
Hello there!
Absolutely, I did use CPU alone and run an assembly examples. It picked up 192 threads and took 9.3 secs to complete. The question beckons: 

1) for a newer GPU with more cores, does it still hold true?
2) Does it scale with larger sequencing data?

This exercise is to investigate if GPU acceleration still have speedup. 
How much effort do you think is needed to get Megahit to compile for CUDA 8? 

Thanks!

Best regards,
James

**Comment by aquaskyline** [comment]
1. Yes, for GTX 1080, it still hold true, the fact is that the bottleneck is still at the memory bandwidth.
2. Yes.

We stopped supporting the GPU version officially because the CPU version is indeed faster, and has a larger user-base. I don't have a good estimation on how much efforts you need to make it work with CUDA 8. From your error message I think you can make it work by removing the PPC related codes from the Makefile.

Good luck.
