### ISSUE TITLE
Any information about k-mer coverage in "log" ?

### ISSUE THREAD

**Issue by tseemann** [voutcn/megahit#17]
I can't seem to find any information about k-mer coverage in the logs.

Is this information available to print?

(It would be per k-mer stage)

Torsten

**Comment by voutcn** [comment]
This info is not available to print at current version.
The average k-mer multiplicity of a contig is tagged in its fasta header (`multi_XXX`).

**Comment by tseemann** [comment]
What do you mean by "average k-mer multiplicity" ?

Is this the average (for each k) of the (average k-mer coverage) per contig ?

**Comment by voutcn** [comment]
Let us take the following header 
`>contig_21_462_length_616_multi_5_in_0_out_0` as an example.

The figure right after `contig_` (i.e. 21) is the *k* used to generate this contig. The figure right after `multi_` is the average k-mer coverage of this contig.

The k-mer coverage is an approximate value for reference only (due to the loss from float to int and an approximate conversion from small *k* to large *k*), so you should be cautious if you need the precise number.

**Comment by tseemann** [comment]
@voutcn Thank you for replying.

Is the length_XXX is in k-mers?

What does the multi_N_in_M_out_X mean?
Does this mean N=5 edges into the node in the graph, and 0 edges out? 
What's the 3rd number mean?

**Comment by voutcn** [comment]
It should be parsed as `multi_C_in_N_out_M` where `C` is the average kmer coverage, `N` is the indegree and `M` is the outdegree.

**Comment by tseemann** [comment]
Thanks for the clarification.
