### ISSUE TITLE
Assembly metrics different?

### ISSUE THREAD

**Issue by kokyriakidis** [voutcn/megahit#179]
Hello!
I am assembling a genome and I saw something frustrating. 
```
The first time I did the assembly with kmin=23, kmax=225 and kstep=6 I found at k=65 N50=19668 contig_bp=1285086554, n_contigs=744125.
``` 
```
The second time I run the assembly with kmin=15, kmax=225 and kstep=2 I found at k=65 N50=18724 contig_bp=1180947106, n_contigs=1032125
```
Why there is such a difference? Can someone explain it to me?  What settings are the best?

**Comment by voutcn** [comment]
Of course they are different because you used different kmin and step.
It is impossible to have one best setting for all assemblies. k_min=15 may be too small and bring many errors in the first step. Starting from 21 should be good for most cases.
Lowering k_min and k_step may be helpful if the sample is sequenced in really low coverage.
