### ISSUE TITLE
Questions about total run time for large metagenomic dataset

### ISSUE THREAD

**Issue by franciscozorrilla** [voutcn/megahit#190]
Hi, this is more of a query than an issue but here it goes:

I am attempting to assemble the dataset from [ERP002469](https://www.ncbi.nlm.nih.gov/sra?term=ERP002469). The dataset consists of ~140 paired end fastq files,  between 2-10 GB in size each, about 1 TB in total. 

Using k list: 27,37,47,57,67,77,87,97,107,117, I am currently running the assembly on a 512 GB RAM node using 20 cores. It has been running for around 30 hours, and the last log entry is: Assembling contigs from SdBG for k = 37 ---

My questions:

- Do you have a rough idea of how long it will take for the entire assembly process to finish on a metagenomic dataset of such size?
- Do you have any additional assembly tips for my particular dataset, besides the ones presented [here](https://github.com/voutcn/megahit/wiki/Assembly-Tips)?
- Are there any pre-assembly steps that you would recommend? e.g. quality score filtering, will this result in a significant improvement in terms of computational time?

Thanks in advance!

**Comment by voutcn** [comment]
Perhaps it is too late to answer.
The running time on small k's is generally longer than large k's. I guess the assembly had already finished in 7 days.

About suggestion on pre-assembly steps.
1. quality trimming is recommended otherwise the number of erroneous k-mers will be huge. 
2. digital normalization with khmer or bbnorm may be applied if the time or memory for assembling the dataset is still unaffordable. I used to do normalization on some viral metagenome datasets, where the sequencing depth of some viral organism can be extremely high.

**Comment by martin-hartmann** [comment]
Sorry to pick up this topic again.

I run megahit on a soil metagenome dataset, but only from one sample for now. These are PE reads of each 4.7Gbp (32M reads each) and one single read file (PEs that were able to be merged) of 13.7 Gbp (60M reads). I am running this on a server with 1TB of RAM and 96 CPUs. Around 4% of the memory and most CPUs are used when monitored via top. It is running with --presets meta-large as recommended for soil metagenomes.

It runs now for 48 hours and is not done yet. These seems to me too long given the benchmalkrs in the paper. What run times do I need to expect given the available computer power and the size and nature of the sequence files? Any help here is greatly appreciated.

Kind regards,
Martin
