### ISSUE TITLE
Handling multimapping reads/orthology/closely related strains

### ISSUE THREAD

**Issue by TealFurnholm** [voutcn/megahit#210]
I work with both cyanobacterial blooms and human scalps, and in both cases the "diseased" condition has reduced diversity but many more strains of the same species. 

Assembling samples separately shows many conserved regions - sometimes even nearly identical contigs - this is very normal/likely since strains will be 95-99% similar. So doing a Co-Assembly, this will definitely be an issue. Even within a sample, from many  metagenome/transcriptome papers, about 30-70% of reads should be multimapping (due to orthologs)

How does MegaHit handle two similar regions in the strain's genomes -> reads -> two similar contigs?

GOOD
--conserved_region--distinct_regionA--
--conserved_region--distinct_regionB--

NOT GOOD
--conserved_region--distinct_regionA--
--distinct_regionB--

AND NOT GOOD EITHER
--conserved_region--
--distinct_regionA--
--distinct_regionB--

**Comment by voutcn** [comment]
Generally speaking, similar regions yield bubbles. Using short reads, it is very difficult to produce the "GOOD" examples. If region A is very similar to region B, the bubble will be merged, i.e., resulting in only one representative contig "--conserved_region--distinct_regionA--" . Otherwise, the assembler may output 3 contigs (--conserved_region--, --distinct_regionA-- and --distinct_regionB-- in your example).
