### ISSUE TITLE
can megahit assemble contigs to scaffolds

### ISSUE THREAD

**Issue by ucassee** [voutcn/megahit#221]
I wonder weather megahit can assemble contigs to scaffolds. 
By the way, I find the output files k*.final.contigs.fa are all empty, is it normal ?

Hope to your reply, thanks in advance~

**Comment by ucassee** [comment]
I am confused with the output file. 
For example, if I set k-mer as k23、k43、 k63、k83、k103、K123， the sequences in  `final.contigs.fa` are the same as `intermediate_contigs/K123.contigs.fa`. In the case, what is the meaning of running  ` k23、k43、 k63、k83、k103`. Can I just run K123 ?

**Comment by voutcn** [comment]
For the first question: no, it does not produce scaffolds.
For the second one, it is normal that k*.final.fa is empty. These files will be non-empty only if `--no-local` is set.
For the last question, no, it is not the same running k=123 only. The contigs of k=123 contain k-mers from the contigs assembled by smaller k's but absent in the original reads. That's why we need to iterate the k-mer sizes.

**Comment by ucassee** [comment]
Hi @voutcn ， I want to know what is the meaning of `--no-mercy`. Could you give me some information about it ?
