### ISSUE TITLE
How to get the reads which formed the contigs in Megahit

### ISSUE THREAD

**Issue by RamaSravanimeduri** [voutcn/megahit#235]
Hi Team,

After running megahit on my data, it gave about 3 million contigs. But now, I need which reads formed these contigs to do further analysis. How to get the corresponding reads R1 and R2.

Thanking you,
Rama.

**Comment by sjaenick** [comment]
You'll need to map them back to the contigs using a short-read aligner, e.g. bowtie2.

**Comment by kislyuk** [comment]
Hi, just wanted to double check - is there no way to recover read information from intermediate assembler output, instead of realigning? Aside from the added complexity, I'm worried that realigning is fundamentally less reliable than getting the read IDs from the assembler - there is no explicit guarantee that the realigned reads will map back to the location where they were used in the assembly.
