### ISSUE TITLE
Question about building SdBG of next k.

### ISSUE THREAD

**Issue by jiarong** [voutcn/megahit#29]
Hi,
I have trouble to understand how megahit build graph of k > min_k. It seems megahit does not read from the original read files for k > k_min. Instead megahit reads in a contig file and multi file and remaining read file. What are the multi file and remaining read file? Why these files will suffice to build graph of next k?
thanks

**Comment by voutcn** [comment]
Good question.
1. the multi file is a file contains the average multiplicity (k-mer coverage) of each contig.
2. Assume that we want to build the graph of k+s from the contigs of k. Two types of reads can be dropped: (a) the reads that are exactly a substring of a contig and (b) the reads whose all (k+s+1)-mers (+1 here because we want to fetch the edges of a de Bruijn graph) cannot aligned back to the graph of k. (b) is possible because we've already clean the graph of k by tips removal etc.. The remaining reads contains at least one (k+s+1)-mer that "spans" a branch in the graph of k.
