### ISSUE TITLE
Broken contigs?

### ISSUE THREAD

**Issue by rrwick** [voutcn/megahit#50]
Thank you for adding FASTG support to MEGAHIT!  I gave it a try on a simple dataset (synthetic reads from a plasmid sequence), and used Bandage to compare the results to Velvet at the same k-mer.

Here's the 61mer Velvet graph:
![velvet_61](https://cloud.githubusercontent.com/assets/7053555/8489612/b75145ee-2160-11e5-9e8a-c93029457b52.png)

And here's the 61mer MEGAHIT graph:
![megahit_61](https://cloud.githubusercontent.com/assets/7053555/8489613/b751a8b8-2160-11e5-88e6-b4f92f83d513.png)

You can see that while they have the same overall structure, some contigs in the MEGAHIT graph are broken into pieces, resulting in 'dead ends'.  It is most notable for one of the long contigs on the left side of the images.  This results in contigs that are not as long as they could be.

The data is fairly ideal (error-free reads and decent read depth), so I'm not sure why this would be happening. I could email you the reads if you wanted to try it for yourselves.

**Comment by voutcn** [comment]
Ryan, please send the reads to voutcn at gmail dot com. I will try it.

**Comment by voutcn** [comment]
Hi Ryan,

Here is the graph of MEGAHIT with parameter `--k-list 61`, which looks the same as that of Velvet:

![image](https://cloud.githubusercontent.com/assets/6329785/8499128/e4880c26-21c1-11e5-9b5a-6c3c960a74b7.png)

Some contigs of MEGAHIT's graph with default parameter are broken because the genome has some closed region that shares very similar patterns, which are merged in *k*=21. For example the long contig on the left is broken around the follow regions:

...**TTCTGCCGCCATTG*A*AGCAAATGCTTTTATACAAAAGG**CACT**TTTCTGCCGCCATTG*G*AGCAAATGCTTTTATACAAAAGG**CACTTTTTTGCTCTCCA...

The two similar patterns in bold are very closed and only differed by 1 bases. A small *k* “collapses” this region, and one of them would be removed as they form a perfect bubble.

Therefore we recommend using larger starting *k* when the sequencing depth is high. But as MEGAHIT targets on metagenomes, where many species are sequenced at low depth, we use a rather small *k*=21 by default.

**Comment by tseemann** [comment]
I agree. MEGAHIT is designed for metagenomes. But in my applications I need a "good" (but not perfect) genome assembly and I need it "fast". I never use k=21 at the lower limit. For 100x  Illumina >100bp PE I would use --min-k 31 or 41 maybe and go as high as 121. I would also set the --min-count to >2, usually something like >10.

@voutcn Are there any other parameters you think we should change when assembling a single bacterium (possibly with a multi-copy higher coverage plasmid) ?

**Comment by tseemann** [comment]
I should probably also use the `--no-mercy` option?

*Mercy k-mer
This is specially designed for metagenomics assembly to recover low coverage sequence. For generic dataset >= 30x, MEGAHIT may generate better results with --no-mercy option.*

**Comment by voutcn** [comment]
@tseemann Yes I suggest so.

**Comment by rrwick** [comment]
Okay, I think I understand this better now.  I had previously assumed that the graph from a 61mer only assembly would be identical to the 61mer graph from an assembly that used a range of k-mers from 21 to 99.  However, it seems that the min k-mer also affects the larger k-mer graphs, due to bubble collapsing.  When I tried the same assembly (k=21 to 99) using the `--no-bubble` option, the graph had no broken contigs.

Thank you for your help!
