### ISSUE TITLE
Optimizing megahit for regular bacterial genomes

### ISSUE THREAD

**Issue by tseemann** [voutcn/megahit#65]
I am trying to optimize megahit for regular bacterial isolate sequencing. We usually have MiSeq, NextSeq or HiSeq reads at high depth, for example paired-end 150bp at about 50x to 150x depth of coverage. So haploid, high depth, close to uniform coverage (not like metagenome).

I have been trying the `-presets bulk` and it does ok, but I feel it should be able to do better. 

What I have found is:
- going from `k=21` all the way to `k=127` is usually better. The higher k-value seems to be very helpful.
- the `--no-mercy` I don't really understand, but it may be making it "worse". But I haven't tested enough.
- the `--min-count 3` seems to work well.

Megahit is so fast that I would like to use it to replace Spades/Velvet/Abyss where I need good, but not 'excellent' assemblies. I don't care if you don't get repeats quite right etc, as long as the unicopy genes turn out ok.

I know there are lots of hidden parameters embedded in the sub-commands, but they are challenging to interpret.

Is there any suggestion you can make for my situation?

**Comment by voutcn** [comment]
Actually, I did not fine tune the `bulk` preset. With your experience, I'd like to upgrade the setting in later versions.

Come back to you situation. Could you share with me your observations when comparing Megahit with Velvet/Spades? In particular, where does Megahit underperform?

I guess for regular bacteria assembly, Megahit is probably too careful in error-pruning (because in metagenome we should be careful in the low-coverage regions). Parameter tuning might not work -- I would like to try some more aggressive algorithms when I have time.

Also, could you suggest some datasets for assembly quality assessment? I've only tried E.coli, but it seemed too simple (Megahit did not underperform Spades in my case).

**Comment by aclum** [comment]
You can check here for how megahit is doing compared other assemblers for
microbial isolates. Please feel free to contribute other docker images & we
are happy to provide microbial isolate datasets.

**Comment by michaelbarton** [comment]
I think @aclum is referring to [nucleotid.es](http://nucleotid.es) for which there is a megahit Docker image, though I believe it's currently out of date.

**Comment by tseemann** [comment]
@michaelbarton That's an excellent idea. I've also got some genomes we have fully closed and validated and corresponding illumina / pacbio / ion torrent reads for. I'm trying to release them soon.

**Comment by voutcn** [comment]
@tseemann 
I've changed the preset for `bulk`. Your suggestions are very helpful. Particularly, `--no-mercy` is needed for some relatively low-depth datasets (~30x). A smaller step, say 10, is useful too.

The latest commit also supports a more aggressive pruning option `--prune-level 3`, which is a *global* pruning, rather than a local one, and may lead to longer contigs. Another new option `--prune-depth` specifies the average k-mer depth threshold to remove a path from the graph. If `--prune-level` is 3, --`prune-depth` is automatically set to *sqrt(median_of_kmer_depth)*, which is the same of Abyss.

I am not able to squeeze much time to test it thoroughly. Hope these could help.

**Comment by davidmartinad200** [comment]
Just in case it can help, and in orther to be able to compre tools there are files out there standardized for bioinformatics benchmarking. It makes things easier when comparing tools.
http://caporasolab.us/mockrobiota/

david
