### ISSUE TITLE
kmin-1pass option

### ISSUE THREAD

**Issue by ukaraoz** [voutcn/megahit#67]
Hi,
Could you provide details on what "kmin-1pass" option does.
Thanks.

**Comment by voutcn** [comment]
To build the kmin-graph, there are 2 steps:
1. kmer counting: input sequences from disk ==> output solid kmers to disk
2. build graph: input solid kmers from disk ==> output succicnt de Bruijn graph to disk

With the kmin-1pass option, it became:
input sequences from disk ==> mark solid kmers (as read_id, offset) in memory with a bit vector ==> build succinct de Bruijn graph from the marked kmers and output to disk

This option is more memory efficient for low-coverage datasets, in which case the memory needed to hold all reads is less than the that to hold all kmers explicitly. But it is slower than the 2-pass method, because identical kmers are not deduplicated after counting.
