### ISSUE TITLE
final contig is exactly the same as k127.contigs.fa

### ISSUE THREAD

**Issue by billzt** [voutcn/megahit#71]
When I running on a Illumina PE 150bp dataset (37X over ~0.8G genome size):
```shell
--min-count 3
--k-list 31,51,71,91,101,111,121,127
--no-mercy
```
I found two strange things:
(1) k31.final.contigs.fa, k51.final.contigs.fa, k71.final.contigs.fa, ..., in intermediate_contigs/ directory are all blank,
(2)The final contig result is exactly the same as k127.contigs.fa (except that final contigs only kept contigs longer than 200bp)

Does this occur just by coincidence? Or inferred some other things?

**Comment by voutcn** [comment]
Yes, it is expected. The naming is a bit confusing, I admit. Please see this post: https://github.com/voutcn/megahit/wiki/contigs-output-by-MEGAHIT

**Comment by billzt** [comment]
Well, after viewing the wiki, question (1) is resolved. However I still concern (2). Why final.contigs.fa is the same as kKmax.contigs.fa.

**Comment by voutcn** [comment]
The iterative k-mers approach actually *iterate* the graph from small k to large k, rather than *combining* the contigs of all those k-mer sizes. In other words, the graph of a large k contains the k-mers that are assembled by small k's.

Therefore final.contigs.fa should be the same as kKmax.contigs.fa., because kmax is the last iteration of the assembly.

**Comment by billzt** [comment]
Thanks for your kindly explanation.
